# No Title

[Original Post](https://discourse.onlinedegree.iitm.ac.in/t/164277/517)

<p>uv run <a href="https://raw.githubusercontent.com/sanand0/tools-in-data-science-public/tds-2025-01/project-1/evaluate.py" rel="noopener nofollow ugc">https://raw.githubusercontent.com/sanand0/tools-in-data-science-public/tds-2025-01/project-1/evaluate.py</a><br>
Installed 13 packages in 543ms<br>
Traceback (most recent call last):<br>
File “/tmp/evaluateF6zgG9.py”, line 20, in <br>
from datagen import (<br>
…&lt;9 lines&gt;…<br>
)<br>
ModuleNotFoundError: No module named ‘datagen’</p>
<p>I am getting this error when I try to run evaluate.py</p>
<p>when I run the evaluate.py by having datagen.py in same folder , it is running perfectly. But my doubt is only after task a1 runs the datagen.py will be downloaded into the /data folder right ?</p>
<p><a class="mention" href="/u/carlton">@carlton</a> <a class="mention" href="/u/saransh_saini">@Saransh_Saini</a> <a class="mention" href="/u/jivraj">@Jivraj</a><br>
Kindly help me with this issue</p>